name: '769_sarcasm'
channels:
  - defaults
  - conda-forge
  - NVIDIA
  - nvidia
dependencies:
  - matplotlib-inline=0.1.6
  - pip=23.3.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pip:
      - accelerate==0.25.0
      - adapters==0.1.0
      - datasets==2.15.0
      - gdown==4.7.1
      - huggingface-hub==0.19.4
      - numpy==1.24.1
      - pandas==2.1.3
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pysocks==1.7.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - tokenizers==0.15.0
      - torch==2.1.1
      - tqdm==4.66.1
      - transformers==4.35.2
      - urllib3==2.1.0
      - yarl==1.9.3
